title: Siscore Visualization
logo: /assets/img/logo.png
description: The official interactive map of 'A human-machine collaborative approach measures economic development using satellite imagery'.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal